plugins:

#  DockerCleaner:
#    force_setup: false
#
#  JavaKiller:
#    force_setup: false

  EnvExpander:
    ignore_vars: [PATH, JAVA_HOME]

  TestResultsCollector:
    version: '1.0.0'
    scope: method
    remote_commands:
      - "zip -v --symlinks -r _logs.zip . -i {include_mask} -x {exclude_mask}"
    download_masks:
      - "_logs.zip"
    unpack_logs: true
